services:

  crypto-lab:
    build: .
    container_name: crypto-pqc-lab

    ports:
      - "127.0.0.1:8888:8888"

    volumes:
      - ./exercises:/workspace/exercises

    working_dir: /workspace

    stdin_open: true
    tty: true
